### ISSUE TITLE
different approach

### ISSUE THREAD

**Issue by gabiudrescu** [Lead-Ext/LeadExtWysiwygEditorPlugin#1]
I was thinking a better approach for this would be to implement a new form theme and this way you can have a global transformation of all textarea fields without any modification in your codebase.

**Comment by kurakin-oleksandr** [comment]
You are not flexible with form theming. F.e. you can not render two textarea with WYSIWYG and one without. I've made PR with custom form type instead. It is much simple than before.

I'm also thinking of auto-init JS script instead of call it manually. How do you like this idea?

**Comment by gabiudrescu** [comment]
yes, indeed, that's a speed bump: if you have two textarea fields and you want WYSIWYG only for one.

but in this case, you can easily decide on a form what form theme you need / want. either on PHP level or on Twig level.

dunno what to say more, having the form theme option sounds more appropriate to me. maybe it's a matter of personal taste.

**Comment by kurakin-oleksandr** [comment]
But there is no possibility to apply theme only for one form field, isn't it?

**Comment by gabiudrescu** [comment]
oh, but it is. you inherit the formtheme from sylius and you override only one form field type. I think.

**Comment by kurakin-oleksandr** [comment]
What form field should be with wysiwyg editor? If you override text area so all text areas will have editor. Anyway you should have custom form type.
